"""baseline: schema before the audit fixes

Revision ID: 0001
Revises: 
"""
import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_api_key_hash'), ['api_key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('uri', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_sha256'), ['sha256'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('consent', sa.Text(), nullable=False),
    sa.Column('contains_people', sa.Boolean(), nullable=False),
    sa.Column('artifact_ids', sa.JSON(), nullable=False),
    sa.Column('annotations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detector_id', sa.String(length=100), nullable=False),
    sa.Column('dataset_id', sa.String(length=32), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_experiment_number')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_status'), ['status'], unique=False)

    op.create_table('experiment_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('code_version', sa.String(length=64), nullable=False),
    sa.Column('detector_version', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_runs_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_runs_status'), ['status'], unique=False)

    op.create_table('patterns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.String(length=32), nullable=True),
    sa.Column('generation_parameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patterns_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patterns_organization_id'), ['organization_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('pdf_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pdf_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_organization_id'), ['organization_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('pattern_id', sa.String(length=32), nullable=True),
    sa.Column('baseline_metrics', sa.JSON(), nullable=False),
    sa.Column('control_metrics', sa.JSON(), nullable=False),
    sa.Column('candidate_metrics', sa.JSON(), nullable=False),
    sa.Column('transformations', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_organization_id'), ['organization_id'], unique=False)

    op.create_table('garments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('pattern_id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=False),
    sa.Column('print_method', sa.String(length=100), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_conditions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garments_pattern_id'), ['pattern_id'], unique=False)

    op.create_table('physical_tests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('pattern_id', sa.String(length=32), nullable=True),
    sa.Column('garment_id', sa.String(length=32), nullable=True),
    sa.Column('arm', sa.String(length=20), nullable=False),
    sa.Column('camera', sa.String(length=200), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('angle_deg', sa.Float(), nullable=True),
    sa.Column('lighting', sa.String(length=200), nullable=False),
    sa.Column('environment', sa.String(length=200), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('artifact_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('physical_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physical_tests_arm'), ['arm'], unique=False)
        batch_op.create_index(batch_op.f('ix_physical_tests_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_physical_tests_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physical_tests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_physical_tests_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_physical_tests_arm'))

    op.drop_table('physical_tests')
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garments_pattern_id'))
        batch_op.drop_index(batch_op.f('ix_garments_organization_id'))

    op.drop_table('garments')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_experiment_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_organization_id'))
        batch_op.drop_index(batch_op.f('ix_reports_experiment_id'))

    op.drop_table('reports')
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patterns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_patterns_experiment_id'))

    op.drop_table('patterns')
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_runs_status'))
        batch_op.drop_index(batch_op.f('ix_experiment_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_runs_experiment_id'))

    op.drop_table('experiment_runs')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_status'))
        batch_op.drop_index(batch_op.f('ix_experiments_project_id'))
        batch_op.drop_index(batch_op.f('ix_experiments_organization_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_organization_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_organization_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifacts_project_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_organization_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_api_key_hash'))

    op.drop_table('users')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    op.drop_table('organizations')
    # ### end Alembic commands ###
