#!/usr/bin/env python3
"""Seed a working VEIL instance and run one experiment end to end.

    python scripts/demo.py                  # colour-blob detector, seconds
    python scripts/demo.py --detector fasterrcnn-mobilenet-320 --image photo.jpg

Prints the API key, the experiment id and the measured results. Everything
it reports is produced by the same code path the API uses.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Run from a checkout whether or not the package is installed: sys.path[0] is
# scripts/, so the repo root has to be added explicitly. Harmless when veil is
# installed, and it survives an editable install that silently did nothing
# (macOS sets UF_HIDDEN on .pth files, which CPython's site.py then skips).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import argparse
import io
import json
from pathlib import Path

import numpy as np
from PIL import Image

from veil.db import create_organization, init_db, session_scope
from veil.ml.runner import execute_run
from veil.models import Artifact, Dataset, Experiment, ExperimentRun, Project
from veil.reports.builder import build
from veil.reports.render import to_pdf
from veil.storage import put_bytes


def synthetic_scene() -> bytes:
    """A dark figure-like shape on a flat background."""
    array = np.full((320, 320, 3), 140, dtype=np.uint8)
    for y1, y2, x1, x2 in ((60, 120, 140, 180), (120, 260, 110, 210),
                           (260, 310, 120, 150), (260, 310, 170, 200)):
        array[y1:y2, x1:x2] = 64
    buffer = io.BytesIO()
    Image.fromarray(array, mode="RGB").save(buffer, format="PNG")
    return buffer.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--detector", default="colorblob-v1")
    parser.add_argument("--label", default=None, help="target label (defaults per detector)")
    parser.add_argument("--image", type=Path, default=None, help="an image you are authorized to use")
    parser.add_argument("--iterations", type=int, default=10)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--out", type=Path, default=Path("var/demo"))
    args = parser.parse_args()

    label = args.label or ("blob" if args.detector == "colorblob-v1" else "person")
    if args.image:
        data = args.image.read_bytes()
    elif args.detector == "colorblob-v1":
        array = np.full((160, 160, 3), 120, dtype=np.uint8)
        array[40:120, 40:120] = (230, 20, 20)
        buffer = io.BytesIO()
        Image.fromarray(array, mode="RGB").save(buffer, format="PNG")
        data = buffer.getvalue()
    else:
        data = synthetic_scene()

    init_db()
    with session_scope() as session:
        org, _, api_key = create_organization(session, "VEIL Demo", "demo@veil.local")
        project = Project(organization_id=org.id, name="Demo project",
                          description="Generated by scripts/demo.py")
        session.add(project)
        session.flush()
        uri, digest, size = put_bytes(org.id, data)
        artifact = Artifact(organization_id=org.id, project_id=project.id, kind="input",
                            uri=uri, media_type="image/png", size_bytes=size, sha256=digest)
        session.add(artifact)
        session.flush()
        dataset = Dataset(organization_id=org.id, project_id=project.id, name="demo scenes",
                          source="synthetic, generated by scripts/demo.py" if not args.image else str(args.image),
                          license="CC0" if not args.image else "user-supplied",
                          artifact_ids=[artifact.id])
        session.add(dataset)
        session.flush()
        configuration = {
            "target_label": label, "threshold": 0.3, "image_size": 320,
            "transforms": {"rotation_deg": [-15.0, 0.0, 15.0], "scale": [1.0],
                           "translate": [0.0], "perspective": [0.0],
                           "brightness": [0.8, 1.0, 1.2], "contrast": [1.0],
                           "blur_sigma": [0.0], "noise_std": [0.0],
                           "deformation": [0.0, 0.03], "mode": "grid", "max_samples": 18},
            "optimization": {"pattern_size": 64, "iterations": args.iterations,
                             "batch_transforms": 2, "learning_rate": 0.08},
        }
        experiment = Experiment(organization_id=org.id, project_id=project.id, number=1,
                                name="Demo robustness sweep", detector_id=args.detector,
                                dataset_id=dataset.id, configuration=configuration)
        session.add(experiment)
        session.flush()
        run = ExperimentRun(organization_id=org.id, experiment_id=experiment.id,
                            status="queued", seed=args.seed, configuration=configuration)
        session.add(run)
        session.flush()
        run_id, experiment_id = run.id, experiment.id

    print(f"API key : {api_key}")
    print(f"experiment: {experiment_id}\nrunning...")
    outcome = execute_run(run_id)
    print(json.dumps(outcome, indent=2))
    if outcome["status"] != "completed":
        return 1

    with session_scope() as session:
        experiment = session.get(Experiment, experiment_id)
        report = build(session, experiment)

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "report.json").write_text(json.dumps(report, indent=2))
    (args.out / "report.pdf").write_bytes(to_pdf(report))
    results = report["results"]
    print(f"\nbaseline  detection rate: {results['baseline']['detection_rate']:.3f}")
    control = results.get("control")
    if control:
        spread = control.get("spread") or {}
        draws = spread.get("draws", 0)
        label = f"mean of {draws} unoptimized" if draws > 1 else "unoptimized"
        print(f"control   detection rate: {control['detection_rate']:.3f}   ({label}, same size)")
        if draws > 1:
            print(f"          draws          : "
                  f"{', '.join(f'{r:.3f}' for r in sorted(spread['rates']))}"
                  f"  (spread {spread['range']:.3f})")
    print(f"candidate detection rate: {results['candidate']['detection_rate']:.3f}")

    # Printed before the score, because it is what qualifies the score.
    attribution = results.get("attribution") or {}
    print("\nattribution")
    if attribution.get("available"):
        print(f"  total drop            : {attribution['total_drop']:+.3f}")
        print(f"  of which occlusion    : {attribution['occlusion_drop']:+.3f}")
        print(f"  the pattern itself    : {attribution['attributable_drop']:+.3f}")
        if attribution.get("attributable_vs_best_control") is not None:
            print(f"  vs. best control draw : {attribution['attributable_vs_best_control']:+.3f}")
        sig = attribution.get("significance") or {}
        if sig.get("available"):
            print(f"  worst p-value         : {sig['worst_p_value']:.4f}  "
                  f"(paired McNemar vs {sig['draws']} draw(s), alpha {sig['alpha']})")
        print(f"  -> {attribution['verdict']}")
    else:
        print(f"  unavailable - {attribution.get('reason', 'no control arm')}")

    print(f"\nVEIL score              : "
          f"{json.dumps({k: v for k, v in results['veil_score'].items() if k.endswith('robustness')}, indent=2)}")
    print(f"\nreport written to {args.out}/report.json and report.pdf")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
