#!/usr/bin/env python3
"""Generate a qualifying synthetic-person dataset and upload it.

    python scripts/seed_scenes.py --api-key "$VEIL_API_KEY" --count 6

Exists so the optimizer can be tested on subjects a detector reliably sees.
The dataset records that it is synthetic; see veil/ml/scenes.py for which
detectors these figures are and are not valid against.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import argparse
import json
import urllib.error
import urllib.request

from veil.ml.scenes import person_png, torso_box


def call(url: str, api_key: str, payload: dict | None = None,
         raw: tuple[str, bytes] | None = None) -> dict:
    if raw is not None:
        boundary = "----veil-boundary"
        name, data = raw
        body = (
            f"--{boundary}\r\nContent-Disposition: form-data; name=\"file\"; "
            f"filename=\"{name}\"\r\nContent-Type: image/png\r\n\r\n"
        ).encode() + data + f"\r\n--{boundary}--\r\n".encode()
        headers = {"X-API-Key": api_key,
                   "Content-Type": f"multipart/form-data; boundary={boundary}"}
        request = urllib.request.Request(url, data=body, headers=headers, method="POST")
    else:
        data = json.dumps(payload).encode() if payload is not None else None
        headers = {"X-API-Key": api_key}
        if data:
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(url, data=data, headers=headers,
                                         method="POST" if data else "GET")
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            return json.loads(response.read())
    except urllib.error.HTTPError as exc:
        sys.exit(f"{exc.code} from {url}\n{exc.read().decode(errors='replace')[:500]}")
    except urllib.error.URLError as exc:
        sys.exit(f"cannot reach {url}: {exc.reason}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api", default="http://localhost:8000/api/v1")
    parser.add_argument("--api-key", required=True)
    parser.add_argument("--project", help="existing project id; a new one is created otherwise")
    parser.add_argument("--count", type=int, default=6)
    parser.add_argument("--size", type=int, default=480)
    parser.add_argument("--detector", default="fasterrcnn-mobilenet-320")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    project = args.project or call(f"{args.api}/projects", args.api_key,
                                   {"name": "Synthetic figures"})["id"]
    artifact_ids, annotations = [], {}
    for index in range(args.count):
        seed = args.seed + index
        artifact = call(f"{args.api}/projects/{project}/artifacts", args.api_key,
                        raw=(f"figure-{seed}.png", person_png(args.size, seed)))
        artifact_ids.append(artifact["id"])
        annotations[artifact["id"]] = [
            {"label": "person", "box": list(torso_box(args.size, seed))}
        ]
        print(f"  uploaded figure {seed} -> {artifact['id'][:8]}")

    dataset = call(f"{args.api}/datasets", args.api_key, {
        "project_id": project, "name": f"synthetic figures x{args.count}",
        "source": "procedurally generated by veil.ml.scenes (no real people)",
        "license": "CC0 (generated in-repo)",
        "contains_people": False,
        "artifact_ids": artifact_ids, "annotations": annotations,
    })

    qualification = call(f"{args.api}/datasets/{dataset['id']}/qualify", args.api_key,
                         {"detector_id": args.detector, "target_label": "person",
                          "threshold": 0.3, "image_size": 320})
    print(f"\nproject    {project}\ndataset    {dataset['id']}")
    print(f"baseline   {qualification['overall']['detection_rate']:.3f}  "
          f"usable={qualification['dataset_usable']}")
    print(f"verdict    {qualification['verdict']}")
    if not qualification["dataset_usable"]:
        print("\nThis dataset will not support a measurable drop.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
